name: CI

on:
  - push
  - pull_request

permissions: {}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch:
          - x64
          - x86
        node:
          - 10
          - 12
          - 14
          - 16
          - 18
          - 20
          - 22
        os:
          - macOS-latest
          - ubuntu-24.04
          - windows-2022
        exclude:
          - arch: x86
            os: macOS-latest
          - arch: x86
            os: ubuntu-24.04
          - arch: x86
            node: 18
            os: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.arch }}
          cache: npm
          cache-dependency-path: ./package.json
      - run: npm install
      - run: npm test
